# Grafana Helm Values
service:
  type: NodePort
  nodePort: 32000

resources:
  requests:
    memory: 64Mi
  limits:
    memory: 128Mi

# Dashboards provisioned automatically from grafana.com
dashboards:
  default:
    node-exporter-full:
      gnetId: 1860
      revision: 37
      datasource: Prometheus

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
