apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k3s-homelab
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Oskar-567/k3s-homelab.git
  ref:
    branch: main
