---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade system packages
  ansible.builtin.apt:
    upgrade: dist

- name: Ensure memory cgroup kernel parameters
  ansible.builtin.include_tasks: cmdline.yml

- name: Reboot if kernel parameters changed
  ansible.builtin.reboot:
    reboot_timeout: 300
  when: cmdline_update is changed
