apiVersion: v1
kind: Service
metadata:
  name: plant-watering-server
  namespace: apps
spec:
  type: NodePort
  selector:
    app: plant-watering-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
